#!/bin/bash

### Add PPA for alacritty & install
sudo add-apt-repository ppa:aslatter/ppa -y
sudo apt-get install alacritty -y

### Symlink zsh config folder to $HOME/.config/zsh (using GNU stow)
stow --verbose --dir=$HOME/.dotfiles zsh

### Install latest version of zsh
sudo apt-get install zsh -y

### Install plugins
sudo apt-get install zsh-autosuggestions

### Change default shell to zsh (does not work reliably!)
sudo chsh -s $(which zsh)

### Link .zshenv file in home directory
ln -s $HOME/.dotfiles/zsh/.config/zsh/.zshenv $HOME/.zshenv

### INSTALL OHMYZSH
ZSH="$HOME/.config/oh-my-zsh" sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

### Remove default .zshrc file generated by installation script
rm $HOME/.zshrc

echo "Finished ZSH installation!"
echo -e "\033[1mNote:\033[0m You may have to run 'sudo chsh -s \$(which zsh)' yourself and you might have to logout and login again for zsh to work!"