#!/bin/bash

### Add PPA for alacritty & install
sudo add-apt-repository ppa:aslatter/ppa -y
sudo apt-get install alacritty -y

### Stow zsh, alacritty, tmux, tmuxinator config to $HOME/.config/...
stow --verbose --dir=$HOME/.dotfiles zsh
stow --verbose --dir=$HOME/.dotfiles alacritty
stow --verbose --dir=$HOME/.dotfiles tmux
stow --verbose --dir=$HOME/.dotfiles tmuxinator

### Install latest version of zsh
sudo apt-get install zsh -y

### Change default shell to zsh (does not work reliably!)
echo "Setting zsh as default shell..."
sudo chsh -s $(which zsh)
sudo -k # invalidate sudo timestamp to execute next command as user
chsh -s $(which zsh)

### INSTALL OHMYZSH
ZSH="$HOME/.config/oh-my-zsh" sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

### INSTALL zsh auto suggestions plugin
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.config/oh-my-zsh/custom}/plugins/zsh-autosuggestions

### Remove default .zshrc file generated by installation script
rm $HOME/.zshrc

echo "Finished ZSH installation!"
echo -e "\033[1mNote:\033[0m You may have to run 'sudo chsh -s \$(which zsh)' yourself and you might have to logout and login again for zsh to work!"