name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testing-github-ci:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "hello world im at $HOME"
      - run: sudo apt install vim
      - run: ls -a
      
  test-installation-scripts:
    name: Test installation scripts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
      - run: tree
      - run: make install
  
      
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     - name: configure
#       run: ./configure

#     - name: Install dependencies
#       run: make

#     - name: Run check
#       run: make check

#     - name: Run distcheck
#       run: make distcheck
